steps:

- name: 'bash'
  args: ['cp', '-r', './common', './ingestors/imf_qnea/common']

- name: 'bash'
  args: ['cp', '-r', './common', './ingestors/imf_fx/common']

- name: 'google/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - imf-qnea-ingestor
  - --gen2
  - --region=australia-southeast2
  - --runtime=python310
  - --source=./ingestors/imf_qnea
  - --entry-point=ingest_imf_qnea_data
  - --trigger-http
  - --no-allow-unauthenticated
  - --memory=1024Mi
  - --timeout=540s

- name: 'google/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - imf-fx-ingestor
  - --gen2
  - --region=australia-southeast2
  - --runtime=python310
  - --source=./ingestors/imf_fx
  - --entry-point=ingest_imf_fx_data
  - --trigger-http
  - --no-allow-unauthenticated
  - --memory=1024Mi
  - --timeout=180s

- name: 'google/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - rss-ingestor
  - --gen2
  - --region=australia-southeast2
  - --runtime=python310
  - --source=./ingestors/rss
  - --entry-point=ingest_rss
  - --trigger-http
  - --no-allow-unauthenticated

- name: 'google/cloud-sdk'
  secretEnv: ['DB_URL']
  args:
  - gcloud
  - functions
  - deploy
  - reverse-etl-news
  - --gen2
  - --region=australia-southeast2
  - --runtime=python310
  - --source=./ingestors/reverse_etl_news
  - --entry-point=ingest_reverse_etl_news
  - --trigger-http
  - --no-allow-unauthenticated
  - --memory=256Mi
  - --timeout=360s

availableSecrets:
  secretManager:
    - versionName: projects/international-finance-484205/secrets/COCKROACH_DB_URL/versions/latest
      env: DB_URL

options:
  logging: CLOUD_LOGGING_ONLY